vim.keymap.set("n", "<Esc>", "<Esc>:nohlsearch<CR>", { silent = true })
vim.keymap.set("n", "<space>{", "?^\\S.*{$<CR>:noh<CR>", { silent = true })
vim.keymap.set("n", "<space>}", "/^}$<CR>:noh<CR>", { silent = true })

-- NOTE: Skip use group key: m -- bookmarks, t -- textmarker
local vscode = require("vscode")
local map = function(mode, lhs, cmd, opts)
  opts = opts or { silent = true }
  vim.keymap.set(mode, lhs, cmd, opts)
end

map("n", "<space><space>", function()
  vscode.call("workbench.action.quickOpen")
end)
map("n", "<space>,", function()
  vscode.call("workbench.action.showAllEditors")
end)
map("n", "<space>s", function()
  vscode.call("workbench.action.gotoSymbol")
end)
-- skip <space>m
map("n", "<space>o", function()
  vscode.call("workbench.action.closeSidebar")
  vscode.call("workbench.action.closeAuxiliaryBar")
  vscode.call("workbench.action.closePanel")
end)
-- skip <space>t
map("n", "<space>z", function()
  vscode.call("workbench.action.toggleZenMode")
end)
-- Enable search: Seed with nearest word
map("n", "<space>/", function()
  vscode.call("workbench.action.findInFiles")
end)

-- clipboard copy/paste
vim.keymap.set("", "<space>y", '"+y')
vim.keymap.set("", "<space>x", '"+dd')
vim.keymap.set("", "<space>p", '"+p')

-- map('n', 'gd', function() vscode.call('editor.action.peekDefinition') end)
-- map('n', 'gD', function() vscode.call('editor.action.revealDefinition') end)
map("n", "gR", function()
  vscode.call("references-view.find")
end)
map("n", "gr", function()
  vscode.call("editor.action.referenceSearch.trigger")
end)
map("n", "gH", function()
  vscode.call("references-view.showCallHierarchy")
end)
map("n", "gh", function()
  vscode.call("editor.showCallHierarchy")
end)
map("n", "gI", function()
  vscode.call("references-view.findImplementations")
end)
map("n", "gi", function()
  vscode.call("editor.action.peekImplementation")
end)

-- bookmarks
map("n", "<space>mm", function()
  vscode.call("bookmarks.toggle")
end)
map("n", "<space>mn", function()
  vscode.call("bookmarks.jumpToNext")
end)
map("n", "<space>mp", function()
  vscode.call("bookmarks.jumpToPrevious")
end)
map("n", "<space>ml", function()
  vscode.call("bookmarks.list")
end)
map("n", "<space>ma", function()
  vscode.call("bookmarks.listFromAllFiles")
end)
map("n", "<space>mc", function()
  vscode.call("bookmarks.clear")
end)
map("n", "<space>me", function()
  vscode.call("bookmarksExplorer.focus")
end)

-- textmarker
map("n", "<space>tt", function()
  vscode.call("textmarker.toggleHighlight")
end)
map("n", "<space>tc", function()
  vscode.call("textmarker.clearAllHighlight")
end)
map("n", "<space>tn", function()
  vscode.call("textmarker.gotToNextHighlight")
end)
map("n", "<space>tp", function()
  vscode.call("textmarker.gotToPreviousHighlight")
end)
